### ISSUE TITLE
@flystorage/stream-mime-type throws an error on dynamic import callback.

### ISSUE THREAD

**Issue by yeoffrey** [duna-oss/flystorage#57]
✅ Willing to contribute to fix this.

Hey! I'm reporting a bug I found today with a setup I have running. We are testing out our implementation of a tool which is using `@flystorage/stream-mime-type`. Upon updating that package to v0.1.3 we now get an error when we run our testing suite:

```
node:internal/modules/esm/utils:226
    throw new ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING_FLAG();
          ^
TypeError: A dynamic import callback was invoked without --experimental-vm-modules
```

## Extra Info
Node: v20.15.1
tsconfig:
```json
{
    "compilerOptions": {
        "incremental": true,
        "module": "commonjs",
        "esModuleInterop": true,
        "target": "es6",
        "noImplicitAny": true,
        "moduleResolution": "node",
        "sourceMap": true,
        "strict": true,
        "outDir": "dist",
        "baseUrl": ".",
        "paths": {
            "*": [
                "node_modules/*"
            ]
        }
    },
}
```
**Note: I ran this in a jest test, which I would say is easiest way to reproduce this error**
## Steps to reproduce
1) Install `@flystorage/stream-mime-type` to version 0.1.2
```shell
npm i @flystorage/stream-mime-type@0.1.2
```
2) Setup a basic `storageAdapter`.
```typescript
const storageAdapter = new FileStorage(new InMemoryStorageAdapter());
```
3) Run that code. Should not error out.
4) Update @flystorage/stream-mime-type to version 0.1.3
```shell
npm update @flystorage/stream-mime-type
```
5) Execute step 3, will error out with the above error.

**Comment by frankdejonge** [comment]
Hi, looking into this now 👍 will report back my findings

**Comment by frankdejonge** [comment]
Version `0.1.4` reverts the change that caused the error. If you could confirm and close the issue, that would be great @yeoffrey

**Comment by yeoffrey** [comment]
Yep fixes things great. Thank you!
