### ISSUE TITLE
Please provide more information about LICENSE

### ISSUE THREAD

**Issue by oanhnn** [duna-oss/flystorage#7]
Thank you for creating a great package.
The open source community will be very happy if you provide more information about the LICENSE of this package.
I hope it will have MIT LICENSE like [Flysystem](https://github.com/thephpleague/flysystem/blob/3.x/LICENSE) package.

**Comment by frankdejonge** [comment]
Hi, the license was already set in the package.json files, but I've added specific license files now too.
