### ISSUE TITLE
Error writing large file from disk to S3

### ISSUE THREAD

**Issue by cadavre** [duna-oss/flystorage#84]
I'm facing an issue when trying to upload a large file from disk (file under a path) to S3.

This simple code:
```ts
const readStream = createReadStream(file.path);
await s3storage.write(path, readStream, {
  mimeType: file.mimetype,
  size: file.size,
});
```

Throws an error when uploading 5GB file:
```
Error: Unable to write the file. Reason: The value of "size" is out of range. It must be >= 0 && <= 4294967296. Received 5_368_709_120
```

How can I upload big files with Flystorage?

**Comment by frankdejonge** [comment]
I was expecting the s3 SDK to handle this gracefully. I'll check this out 👌

**Comment by frankdejonge** [comment]
<img width="899" alt="Screenshot 2024-11-22 at 08 53 22" src="https://github.com/user-attachments/assets/e2ad46fb-f977-43e9-bf59-460bcf8b347a">
It might have something to do with bucket configuration? I've just uploaded a 6g blob to S3 using flystorage and it (took a bit of time but) worked.
