### ISSUE TITLE
LocalStorageAdapter writes not returning when awaited

### ISSUE THREAD

**Issue by koder24** [duna-oss/flystorage#86]
When using the LocalStorageAdapter and doing a write the promise never resolves or rejects causing it to hang indefinitely. 

### Environment

```
Ubuntu (WSL) - 22.04
Node.js - 16.16 
@flystorage/file-storage - ^0.1.5
@flystorage/local-fs - ^0.1.7
```

**Comment by frankdejonge** [comment]
@koder24 could you send a script to replicate this behaviour? This seems very unlikely. Would help if you share some of your environment setup too.

**Comment by koder24** [comment]
I updated the description to include a few versions. I can try to work something up over the next few days. I suspect it's an issue with our node version (which we know is very old, this is for a legacy deployment). This PR https://github.com/duna-oss/flystorage/pull/87 resolves the issue for us though when we test locally.
